### ISSUE TITLE
Grounding for coolant water

### ISSUE THREAD

**Issue by ri0t** [c-base/c-lazor#11]
Since it may come into contact with the HV section, it needs a stainless steel grounding anchor. I was told that the skipper volunteered to provide us with one. A simple v4a steel bolt would already help.

**Comment by ri0t** [comment]
The pump is a submersible type and has a SchuKo-Stecker. Should already be grounded somewhat. Probably not meant for the lazors' PSU voltage.

**Comment by ForsakenHarmony** [comment]
Done 🎉
